server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

cloud:
  gateway:
    routes:
      - id: service-a-route
        uri: lb://service-a
        predicates:
          - Path=/api-a/**
        filters:
          - AddRequestHeader=X-Request-Foo, Bar

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.boot.actuate.metrics.web.reactive.server: DEBUG